### ISSUE TITLE
Discord webhook not working

### ISSUE THREAD

**Issue by mpellicc** [zip6como/hanime-auto-coins-plus#4]
Following your tutorial (step "Configuring the webhook" of Windows tutorial), I configured the Discord webhook in a text channel. The script ran and the house.txt file is correctly populated, but it didn't send the text on Discord.
The channel is a restricted one, but I checked and that shouldn't be a problem for the webhook.

OS: Windows 11
Discord version: Stable 215909
Python version: 3.11.4

`house.txt`
![image](https://github.com/zip6como/hanime-auto-coins-plus/assets/42090014/2355d72b-9797-48e0-8536-e34325ff8fef)

Feel free to ask for more details. While writing this the script run again and the problem is still there.

**Comment by zip6como** [comment]
Hello,

Can you please upload a screenshot of your webhook.py file?
It also would be useful if you would help me if you would run a test of your webhook with https://disforge.com/tool/webhook-tester and tell me if it worked.

**Comment by mpellicc** [comment]
As soon as I tested the webhook it has also sent the previous messages from your script.

I guess it's working now, but I'll paste my webhook.py anyway:
```
#THIS FILE SENDS THE HOUSE.TXT FILE CONTENT TO THE WEBHOOK
import requests

def send_to_discord_webhook(webhook_url, file_path):
    try:
        # Read the content of the file
        with open(file_path, 'r') as file:
            content = file.read()

        # Prepare the payload to be sent to the Discord webhook
        payload = {
            'content': content
        }

        # Send the payload to the webhook URL
        response = requests.post(webhook_url, json=payload)

        # Check if the request was successful
        if response.status_code == 204:
            pass
        else:
            print("Failed to send content to Discord. Status code:", response.status_code)

    except FileNotFoundError:
        print("File not found. Please check the file path.")

#THIS IS TO CONFIGURE THE WEBHOOK
if __name__ == "__main__":
    webhook_url = "https://discord.com/api/webhooks/1134543086677151855/7xuC36K2iyCA-xWKRYBCfaBlIfBM_oE_wahzDjJcn2043RdHb0rmTDnU1UU3Qx3wg_Zj"
    file_path = "house.txt"  # Update the file path accordingly
#-CONFIG END-

    send_to_discord_webhook(webhook_url, file_path)
```

**Comment by zip6como** [comment]
The file looks right to me, you did nothing wrong.
Oh, yes, since the script is hosted on your local machine and internet; local issues like queue ups can happen.
Please keep an eye on it and check if it works or not.
If the issue remains, just comment again here.
If you don't comment again in the next 30 days, I will assume everything works and close the issue.
