### ISSUE TITLE
Autorun not working [Everything else works]

### ISSUE THREAD

**Issue by BalajiX5** [zip6como/hanime-auto-coins-plus#5]
Tried the whole new updated tutorial, everything works except the last part i.e the Autorun of the [WIN-autorun.bat]. Runs manually even in the task scheduler [pressing right click ].

**Comment by zip6como** [comment]
When you are running the script manually in the task scheduler, does a cmd popup and close itself?

**Comment by zip6como** [comment]
@BalajiX5 It's really weird I tested the script to run every 5 mins, and it works for me.
Could you please provide screenshots of your WIN-autorun.bat file?
And screenshots of your task scheduler task.

**Comment by BalajiX5** [comment]
Task Scheduler Screenshots
![Screenshot (38)](https://github.com/zip6como/hanime-auto-coins-plus/assets/125268449/ef5b9404-cf9c-4756-bb4a-aa82e452b9ab)
![Screenshot (39)](https://github.com/zip6como/hanime-auto-coins-plus/assets/125268449/6f34bb33-1d3f-48ca-ae43-2c9422c21e17)
![Screenshot (40)](https://github.com/zip6como/hanime-auto-coins-plus/assets/125268449/fa28b6e9-8970-4bf6-807c-b76bd9a45990)
![Screenshot (41)](https://github.com/zip6como/hanime-auto-coins-plus/assets/125268449/56306f89-6b87-463d-8ae2-7d13c2d874f7)
![Screenshot (42)](https://github.com/zip6como/hanime-auto-coins-plus/assets/125268449/e11a462f-d069-4311-a76b-942c10fad31a)
![Screenshot (43)](https://github.com/zip6como/hanime-auto-coins-plus/assets/125268449/fb37a497-806f-4518-b48a-fc932b798ca3)
![Screenshot (44)](https://github.com/zip6como/hanime-auto-coins-plus/assets/125268449/f49b13e9-6bb8-4719-9f5f-796fe42a6ad5)

**Comment by BalajiX5** [comment]
@zip6como 
here's the WIN-autorun.bat screenshot. sorry for the delay.
![Screenshot (45)](https://github.com/zip6como/hanime-auto-coins-plus/assets/125268449/cd0941f4-a34d-42cc-b817-5f3a5563f58b)

**Comment by zip6como** [comment]
Hmm... This is really strange.
I don't see any problems with your configuration.
In the WIN-autorun.bat, could you please try to replace the: timeout /t 0 /nobreak >nul
with: timeout /t 1 /nobreak >nul

And are you really sure the script doesn't autorun?

**Comment by BalajiX5** [comment]
@zip6como  
yes the script doesn't autorun.
after changing : timeout /t 0 /nobreak >nul with: timeout /t 1 /nobreak >nul
it still doesnt auto run!

**Comment by zip6como** [comment]
Hmm, weird ...
Does a cmd popup for 1sec, or does nothing happen at all?

**Comment by BalajiX5** [comment]
@zip6como 
I changed this value and now the cmd starts on startup and i waited 5 mins and now autorun works after 5 mins. i donno what the hell happened.
![Screenshot (47)](https://github.com/zip6como/hanime-auto-coins-plus/assets/125268449/b81230a9-12c2-4e5a-91b2-1bf8e92da022)

**Comment by zip6como** [comment]
Does this mean the script now runs every 5 mins?

**Comment by BalajiX5** [comment]
@zip6como 
now the script runs every 5 mins

**Comment by zip6como** [comment]
So everything works, right?
Is the issue you had now resolved?

**Comment by BalajiX5** [comment]
so now i think when i start my pc, the cmd will run once and then after every 3 hour it will autorun. _[maybe the error was trying to start on a schedule]_

Now everything works man. Thanks for all the support @zip6como    you are the best!!

**Comment by zip6como** [comment]
@BalajiX5 Glad I could help.
I will update the tutorial to autostart the script like you did.
If you like this repository, could you please "star" it?

**Comment by BalajiX5** [comment]
Yes it is a wonderful script and helped me tremendously. I have starred it and follow this repository.
Thanks for your assistance in solving my issue. 
@zip6como  **_Best of wishes to you_**
